implemented mergefinder method and fixed a bug
In the full svn:mergeinfo XML file, there are several property
elements that contain only whitespace.  This was causing
"AttributeError: 'NoneType' object has no attribute 'splitlines'"